#include <QAction>
#include <QApplication>
#include <QBuffer>
#include <QByteArray>
#include <QCheckBox>
#include <QClipboard>
#include <QColor>
#include <QComboBox>
#include <QDateTime>
#include <QDebug>
#include <QDialog>
#include <QDir>
#include <QDrag>
#include <QFile>
#include <QFlags>
#include <QFrame>
#include <QHBoxLayout>
#include <QHash>
#include <QHeaderView>
#include <QIcon>
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QJsonValue>
#include <QLabel>
#include <QLineEdit>
#include <QList>
#include <QMap>
#include <QMenu>
#include <QMessageBox>
#include <QMetatype>
#include <QMimeData>
#include <QMouseEvent>
#include <QPainter>
#include <QPalette>
#include <QPixmap>
#include <QPointer>
#include <QProcess>
#include <QPushButton>
#include <QRadioButton>
#include <QScrollBar>
#include <QSpacerItem>
#include <QSslCertificate>
#include <QStackedLayout>
#include <QStackedWidget>
#include <QStringList>
#include <QStyle>
#include <QSysInfo>
#include <QTabWidget>
#include <QTemporaryFile>
#include <QTextDocument>
#include <QTimer>
#include <QToolButton>
#include <QToolTip>
#include <QUrl>
#include <QUrlQuery>
#include <QVBoxLayout>
#include <QVariant>
#include <QVector>
#include <QWebEngineContextMenuData>
#include <QWebEngineHistory>
#include <QWebEnginePage>
#include <QWidget>
//#include <QPrintDialog>
//#include <QPrinter>
//#include <QQuickWidget> pb avec macro "interface"
